### ISSUE TITLE
İnstallation

### ISSUE THREAD

**Issue by mehmetsarr** [hmislk/hmis#418]
Hello, thank you very much to everyone who contributed to the project. Is there a tutorial video you can recommend for installation?

**Comment by buddhika75** [comment]
The details of the installation are described in the wiki. We would love to do a video, but no resources available yet. Will do an update here. Thank you.

**Comment by mehmetsarr** [comment]
Thank you 🙂👍

**Comment by mehmetsarr** [comment]
> Kurulumun detayları wikide açıklanmıştır. Video çekmeyi çok isterdik, ancak henüz kaynak yok. Burada bir güncelleme yapacak. Teşekkür ederim.

@buddhika75 
So can we run it on windows 7 xampp?

**Comment by buddhika75** [comment]
> > Kurulumun detayları wikide açıklanmıştır. Video çekmeyi çok isterdik, ancak henüz kaynak yok. Burada bir güncelleme yapacak. Teşekkür ederim.
> 
> @buddhika75
> So can we run it on windows 7 xampp?

No. We can not use plane xampp. You have to convert Tomcat in to Tomee. Please refer to the [wiki ](https://github.com/hmislk/hmis/wiki/Deployment-in-a-Development-Environment) for details.

[https://github.com/hmislk/hmis/wiki/Deployment-in-a-Development-Environment](https://github.com/hmislk/hmis/wiki/Deployment-in-a-Development-Environment)

**Comment by simendipeter** [comment]
hie. how do i get to the login screen

**Comment by tamerrab2003** [comment]
when you finish installation/configuration and deploy it by netbeans on glassfish, it should open your default browser with the following URI:
http://localhost:8080/hmis-master/

If its not opened then you have issue with your installation/configuration.

**Comment by azharshaikh7866** [comment]
> when you finish installation/configuration and deploy it by netbeans on glassfish, it should open your default browser with the following URI:
> http://localhost:8080/hmis-master/
> 
> If its not opened then you have issue with your installation/configuration.

No it goes to http://localhost:8080/hmis/

**Comment by teeveekay** [comment]
HI iam new to  java.i did whatever said in installation manual.but when i run the program getting following error.

Severe:   Exception while deploying the app [arogya] : Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.1.v20150605-31e8258): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Class name is wrong or classpath is not set for : com.mysql.jdbc.jdbc2.optional.MysqlDataSource
Error Code: 0
Warning:   
can you explain what i did wrong.

**Comment by buddhika75** [comment]
Please use payara or glassfish to create a connection pool. Then create a connection. Give its connection name in the persistence file. I will upload a video and give you the link.

**Comment by teeveekay** [comment]
HI,Waiting for your reply.After successful run i can add institution,departments but i can't add user so i need your support where to start from..or kindly share the demo data if you have.

**Comment by teeveekay** [comment]
Hello , I am waiting for your reply , not to able to use the application and getting an error "NOT AUTHORISED" kindly help me out and need your support Thank you

**Comment by teeveekay** [comment]
I successfully logged into the application and gone through the admin module, pharmacy etc., but I do not know how to use some of the modules like lab, HRM modules in your software, So I need your  support for user training. Kindly update me .

**Comment by Ippezrobert** [comment]
Hey all, thanks for the great work.... However am trying to setup development environment but am getting errors as below: Any assistance will be highly appreciated

Am using:-
Windows 11
Netbean 12.6
GlassFish Server 4.1.2
MySQL Server 5.0.90 

**_Severe:   Exception during lifecycle processing
java.lang.RuntimeException: EJB Timer Service is not available
	at com.sun.ejb.containers.BaseContainer.startApplication(BaseContainer.java:4009)
	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:163)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:352)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:500)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:748)

Severe:   Exception while loading the app
Severe:   Undeployment failed for context /hmis
Warning:   EJB Timer Service is not available. Timers for application with id 107940896189644800 will not be deleted
Info:   /file:/D:/hmis/target/arogya-2.0-SNAPSHOT/WEB-INF/classes/_hmisPU logout successful
Severe:   Exception while loading the app : EJB Timer Service is not available
Warning:_** 

Thanks and regards

**Comment by Ippezrobert** [comment]
@buddhika75 can we have it tomorrow at 10:30am IST

thanks

**Comment by Ippezrobert** [comment]
I have created a meeting to help those of us who have never succeeded in running the application, any interested person can join by the link below 

**Guidance through Installation Process of HMIS by Dr. M H B Ariyaratne**

Time: **Tuesday, October 25⋅10:30 – 11:00am IST** · 

**Google Meet joining info**
Video call link: https://meet.google.com/iis-rgqe-xwc

**Comment by buddhika75** [comment]
I am ready. Can I have email address to share the calender event.

Regards,

**Comment by Ippezrobert** [comment]
ippezrobert@gmail.com

**Comment by buddhika75** [comment]
I am logged in. please let me in

**Comment by Ippezrobert** [comment]
Iam logged in too...

**Comment by mnomansadiq** [comment]
Hi, Thanks for sharing the great work, I am actually getting a problem deploying the war file, it seems that the connection pool name mentioned in the installation notes is different in actuality so that getting the following error:

`remote failure: Error occurred during deployment: Exception while deploying the app [arogya22-3.0.0] : JNDI lookup failed for the resource: Name: [hmisPU], Lookup: [jdbc/rh], Type: [javax.sql.DataSource]. Please see server.log for more details.`


I tried to change the JNDI lookup name added: jndi/hmisPU but no luck, Any hint to resolve that?

**Comment by mnomansadiq** [comment]
> http://localhost:8080/hmis-master/

Can you please share how you resolve it?

**Comment by mnomansadiq** [comment]
> when i change RUN configuration, project run in browser but get an following error. ![error](https://user-images.githubusercontent.com/92254066/138582896-a3589d9a-d19e-4866-8920-1fb5cac74b21.png)

Can you please share how you resolve it?

**Comment by buddhika75** [comment]
Create a Java Connection with the name as in the persistance.xml file

[****](https://docs.google.com/document/d/1GA4WnRvMF78P-ugpjzziT_0Vke0bnVGjkgfJrY5z8ao/edit?usp=sharing)

**Comment by mnomansadiq** [comment]
> Create a Java Connection with the name as in the persistance.xml file
> 
> [**Link**](https://docs.google.com/document/d/1GA4WnRvMF78P-ugpjzziT_0Vke0bnVGjkgfJrY5z8ao/edit?usp=sharing)

I think I have a same.

<img width="973" alt="Screenshot 2022-12-01 at 17 34 56" src="https://user-images.githubusercontent.com/11539579/205108742-7a845e4a-f12b-4db1-a5e1-4f6340d14b90.png">
<img width="1063" alt="Screenshot 2022-12-01 at 17 35 11" src="https://user-images.githubusercontent.com/11539579/205108755-99a99195-3d4c-4642-b632-4517339eec4d.png">
<img width="951" alt="Screenshot 2022-12-01 at 17 35 42" src="https://user-images.githubusercontent.com/11539579/205108765-a520d142-2963-4dd1-a0c2-0c841ee38723.png">

**Comment by buddhika75** [comment]
The tables are NOT created it seems. Need to add table generation strategy 
 <property name="javax.persistence.schema-generation.database.action" value="create-or-extend-tables"/>

Full FIle as below


<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
    <persistence-unit name="hmisPU" transaction-type="JTA">
        <jta-data-source>jdbc/rh</jta-data-source>
        <exclude-unlisted-classes>false</exclude-unlisted-classes>
        <shared-cache-mode>ALL</shared-cache-mode>
        <properties>
            <property name="javax.persistence.schema-generation.database.action" value="create-or-extend-tables"/>
        </properties>
    </persistence-unit>
</persistence>
