### ISSUE TITLE
facing issue while doing Installation on development machine

### ISSUE THREAD

**Issue by ap-zed** [hmislk/hmis#529]
Hi,

Appreciate your hard work on this repository/project.

We have been trying to run the project in the development machine but couldn't able to do that.

Have installed all the requirements as per the INSTALL_GUIDE.me file in the master branch.

we are getting the following error. If anyone can help with that.

com/divudi/ws/lims/Lims.java:[83,144] cannot access org.hl7.fhir.instance.model.api.ICompositeType
  bad class file: C:\Users\iDreams\.m2\repository\ca\uhn\hapi\fhir\hapi-fhir-base\6.1.3\hapi-fhir-base-6.1.3.jar(org/hl7/fhir/instance/model/api/ICompositeType.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

Let me know if you need any further information.

Thanks,

**Comment by ap-zed** [comment]
same error with different message - Class org.hl7.fhir.r5.model.OperationOutcome has unsupported major or minor version numbers, which are greater than those found in the Java Runtime Environment version 1.8.0_191

**Comment by buddhika75** [comment]
What is the JDK version you use? Can you please try JDK 11 ?

**Comment by buddhika75** [comment]
We are not getting this error, can you post the full error log.

**Comment by ap-zed** [comment]
Thanks for the response, Let me try with the JDK 11, and will update you.

**Comment by ap-zed** [comment]
@buddhika75 - the project was built successfully with JDK11. now getting this error while add JDBC connection pool.

  RAR5099 : Wrong class name or classpath for Datasource Object 
java.lang.ClassNotFoundException: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.sun.gjc.common.DataSourceObjectBuilder.getDataSourceObject(DataSourceObjectBuilder.java:285)
	at com.sun.gjc.common.DataSourceObjectBuilder.constructDataSourceObject(DataSourceObjectBuilder.java:114)
	at com.sun.gjc.spi.ManagedConnectionFactoryImpl.getDataSource(ManagedConnectionFactoryImpl.java:1300)
	at com.sun.gjc.spi.DSManagedConnectionFactory.getDataSource(DSManagedConnectionFactory.java:163)
	at com.sun.gjc.spi.DSManagedConnectionFactory.createManagedConnection(DSManagedConnectionFactory.java:102)
	at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.getUnpooledConnection(ConnectorConnectionPoolAdminServiceImpl.java:702)
	at com.sun.enterprise.connectors.service.ConnectorConnectionPoolAdminServiceImpl.testConnectionPool(ConnectorConnectionPoolAdminServiceImpl.java:431)
	at com.sun.enterprise.connectors.ConnectorRuntime.pingConnectionPool(ConnectorRuntime.java:1162)
	at org.glassfish.connectors.admin.cli.PingConnectionPool.execute(PingConnectionPool.java:143)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:253)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:231)
	at org.glassfish.admin.rest.resources.TemplateExecCommand.executeCommandLegacyFormat(TemplateExecCommand.java:157)
	at org.glassfish.admin.rest.resources.TemplateCommandGetResource.processGetLegacyFormat(TemplateCommandGetResource.java:75)
	at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:309)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:292)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1139)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:375)
	at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:316)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:179)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:748)
|#]
  RAR8054: Exception while creating an unpooled [test] connection for pool [ DerbyPool ], Class name is wrong or classpath is not set for : com.mysql.cj.jdbc.MysqlConnectionPoolDataSource|#]
  RestResponse.getResponse() gives FAILURE.  endpoint = 'http://localhost:4848/management/domain/resources/ping-connection-pool.json'; attrs = '{id=DerbyPool}'|#]

**Comment by buddhika75** [comment]
It is because you have no JDBC driver. Use MySQL JDBC Driver 8.0.17. You
need to add the jar file to Payara. you can do it through asadmin or by
copying the files to domains lib folder and lib/extension folder. Also
select MySQL8 driver in creating a connection pool.

https://youtu.be/5gqk4jFmEkU

**Comment by ap-zed** [comment]
Hi,

I have been followed all the instructions but still not able to deploy the project into development machine.

Getting server time out error.

--------Server.log--------

[2023-05-01T12:29:44.173+0530] [Payara 5.2022.3] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=232 _ThreadName=admin-thread-pool::admin-listener(6)] [timeMillis: 1682924384173] [levelValue: 800] [[
  Redirecting to /]]

[2023-05-01T12:29:44.504+0530] [Payara 5.2022.3] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=230 _ThreadName=admin-thread-pool::admin-listener(4)] [timeMillis: 1682924384504] [levelValue: 800] [[
  Admin Console: Initializing Session Attributes...]]

[2023-05-01T12:29:59.783+0530] [Payara 5.2022.3] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=143 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1682924399783] [levelValue: 1000] [[
  Class org.hl7.fhir.r5.model.OperationOutcome has unsupported major or minor version numbers, which are greater than those found in the Java Runtime Environment version 1.8.0_191]]

[2023-05-01T12:30:17.370+0530] [Payara 5.2022.3] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=220 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1682924417370] [levelValue: 800] [[
  GUI deployment: uploadToTempfile]]

[2023-05-01T12:30:17.376+0530] [Payara 5.2022.3] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=220 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1682924417376] [levelValue: 800] [[
  uploadFileName=arogyaOhmis-3.0.0.war]]

[2023-05-01T12:30:17.517+0530] [Payara 5.2022.3] [INFO] [] [] [tid: _ThreadID=220 _ThreadName=admin-thread-pool::admin-listener(3)] [timeMillis: 1682924417517] [levelValue: 800] [[
  ================== availabilityEnabled  skipped ]]

------------------------------------------------------------------------------------------------- 



![image](https://user-images.githubusercontent.com/11896328/235421384-6456e944-6a31-450b-8ead-99f5ce609b3a.png)
